#ifndef _SYNTAX_SYMBOL_H
#define _SYNTAX_SYMBOL_H

//语法结构类型，用来记录当前分析到的语法结构
enum syntax_symbol
{
  INIT,
  IF_SYMBOL,
  ELIF_SYMBOL,
  ELSE_SYMBOL,
  WHILE_SYMBOL,
  DO_SYMBOL,
  FOR_SYMBOL,
  WHILE_OF_DO,
  BLOCK_IN,
  SENTENCE_IN,
  LEFTBRA,
  LEFTPAR,
  DO_WHILE_BLOCK_IN,
  DO_WHILE_BLOCK_OUT,
  DO_WHILE_CASE_IN,
  DO_WHILE_CASE_OUT,
  IF_CASE_IN,
  IF_CASE_OUT,
  IF_BLOCK_IN,
  IF_BLOCK_OUT,
  ELIF_CASE_IN,
  ELIF_CASE_OUT,
  ELIF_BLOCK_IN,
  ELIF_BLOCK_OUT,
  ELSE_BLOCK_IN,
  WHILE_CASE_IN,
  WHILE_CASE_OUT,
  WHILE_BLOCK_IN,
  FOR_INIT_IN,
  FOR_CONDITION_IN,
  FOR_REFRESH_IN,
  FOR_REFRESH_END,
  FOR_BODY_IN,
  Symbols_NUM
}Symbol;




#endif